name: notes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  alarm: ^3.0.6
  flutter:
    sdk: flutter
  flutter_quill: ^9.2.10
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - 'lib\assets\pencil (1).png'
